language: python
python:
  - '3.5'
  - '3.6'
  - '3.7'
install:
  - pip install -r requirements.txt
  - pip install pytest
script:
  - pytest
deploy:
  provider: pypi
  user: codechenx
  password:
    secure: n5BsKxBrw/kFC5KLILlgRSEL4F+lqWHkAOIHslOkawla7vrW+Fva5Vr08jY3mZz2WdkSdCLZZDwOgYWjTW2z+ze3HrZ7iz2cu/k4fRvmuvGODpSCwplbHoHekX+FR0boLJEGGHu/eSqhTY76WceGk07R3jwJX6nPUJTLZ4O5gqTTlJdWCzMYfqCECRfbi/NibJcAinHBt9whEWzvAQfDfEtAT1SunJ1wv7y6xcJucYfVA/Qb5+fjd+bcM7ur1NTBBTBeVX6Mua1UxIsl2LGs/FiwXRz6uJNfY6W1P6mB1yOibJaSHKiRNx3I87rQSDYYJrw7s/xFrSAyk+97Mamk8VUxMxPBVx7ir0/UbC5vq9XG/k6FTr9G+yQKJD7lYThe4XTHZPhVE9beS33g6HP2aIQ0mKMETUYa9Hz433Om1k2abjy1So96zTr4yR10MomdA+qzF4ISjP3c3edK7x+TbJF71LBrwb5aHJCFXr1t2rtUyxtwccoXGbCSDG+JvvJN6psjbD5CpUfxcWXz/yhTO1BOpBXTLD5nMyRROofPuNRzkJbG3r89zKpf1z4ng5cdhhcFNKL0c86Gnn4arUmyudEutmKO7YK2rXKsb4mCLzq3nW0XfCjmFrrpwKshu2TKgN7p59loVUEZ2JRuhwUeE+sO+BjunvkTyUYI7aL5010=
  on:
    tags: true
    branch: master
