{% set name = "bv" %}
{% set version = "0.1.4" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: cd65902a4aaa0818da7cb8a38ca4ec82d47d4e6d7bc6982509effc080be8fc95

build:
  number: 0
  entry_points:
    - bv=bv:bv
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - chardet
    - openpyxl
    - pip
    - python  {{ python }}
  run:
    - chardet
    - openpyxl
    - python  {{ python }}

test:
  imports:
    - bv
  commands:
    - bv --help

about:
  home: https://github.com/codechenx/bv
  license: MIT
  license_family: MIT
  license_file: 
  summary: Data Viewer in Terminal for Bioinformatician
  doc_url: 
  dev_url: 

extra:
  recipe-maintainers:
    - codechenx
